### ISSUE TITLE
Contact page design

### ISSUE THREAD

**Issue by maryrachel** [fcflamingo/fcflamingo-rails#11]
-Embed video
-Reposition text
![screen shot 2015-04-10 at 4 18 52 pm](https://cloud.githubusercontent.com/assets/1198517/7099261/90e66e10-dfa3-11e4-809c-8213b995ccc0.png)

**Comment by gloh** [comment]
@maryrachel add mobile design as well

**Comment by nickyrasch** [comment]
https://www.youtube.com/watch?v=IBfUFkni-QU&feature=youtu.be
